__author__ = 'pascalpoizat'

from pyArduinoML.model.NamedElement import NamedElement
from pyArduinoML.model.Monitor import Monitor

class App(NamedElement):
    """
    Application built over bricks.

    """

    def __init__(self, name: str, bricks: tuple=(), states: tuple=(), monitor: Monitor=None):
        """
        Constructor.

        :param name: String, the name of the application
        :param bricks: List[Brick], bricks over which the application operates
        :param states: List[State], states of the application with the first one being the initial state
        :return:
        """
        NamedElement.__init__(self, name)
        self.bricks: tuple = bricks
        self.states: tuple = states
        self.monitor: Monitor = monitor

    def __repr__(self):
        """
        External representation: Arduino program

        :return: String
        """
        print(self.bricks)
        rtr = """// generated by ArduinoML

%s

void setup() { %s """ % ("\n".join(map(lambda b: b.declare(), self.bricks)),
                        "\n".join(map(lambda b: b.setup(), self.bricks)))

        if self.monitor is not None:
            rtr += self.monitor.setup()

        rtr += """
        
        }

void (*functionPtr)() = state_%s;
int state = LOW; int prev = HIGH;
long time = 0; long debounce = 200;

%s
void loop() { (*functionPtr)(); """ % (
                                  self.states[0].name,
                                  "\n".join(map(lambda s: s.setup(), self.states)))


        if self.monitor is not None:
            rtr += self.monitor.loop()
        rtr += "}" 


        return rtr
